### ISSUE TITLE
attempt to select less than one element in get1index

### ISSUE THREAD

**Issue by Dediggefedde** [zeehio/facetscales#15] opened 2020-02-26 20:37 UTC
Hi! Thank you for the script! I needed something like this a lot of times in the past.

However, when I installed it using 
`devtools::install_github("zeehio/facetscales",force=T)`
and using your sample code from this github page, I got an error:

> Fehler in .subset2(x, i, exact = exact) : 
>   attempt to select less than one element in get1index 

Also, all the other tries to use it result in an error as well.
I use the default install of R (3.6.2) on a Win10 64bit machine.

Is the current version working? Or might there be a problem with my R configuration?

**Comment by zeehio** [comment] 2020-02-28 08:24
It should work, tests are passing. Please use an updated scales and ggplot2 version. Otherwise provide a reproducible example created with the reprex package.

https://www.tidyverse.org/help/#reprex

**Comment by Dediggefedde** [comment] 2020-02-28 09:27
Thanks for the quick answer!
I have the latest scales and ggplot2 package.

I try to run your sample program:
``` r
library(ggplot2)
library(scales)
library(facetscales)
mydf <- data.frame(
  Subject = rep(c("A", "B", "C", "D"), each = 4),
  Magnitude = rep(c("SomeValue", "Percent", "Scientific", "LogScale"), times = 4),
  Value = c(c(170, 0.60, 2.7E-4, 10000),
            c(180, 0.80, 2.5E-4, 100),
            c(160, 0.71, 3.2E-4, 1000),
            c(159, 0.62, 3.0E-4, 10)))

scales_y <- list(
  Percent = scale_y_continuous(labels = percent_format()),
  SomeValue = scale_y_continuous(),
  Scientific = scale_y_continuous(labels = scientific_format()),
  LogScale = scale_y_log10()
)

ggplot(mydf) +
  geom_point(aes(x = Subject, y = Value)) +
  facet_grid_sc(rows = vars(Magnitude), scales = list(y = scales_y))
```
When I run reprex() the viewer shows me the image as it should be (see below).
When I select all and press "run" (ctrl+return) the error occurs.
When I source the file (with a print(ggplot(...)) ) the error also occurs. 

I don't understand why the script is working fine with reprex(), but not directly in a .r script. Does it need an active project or rmarkdown file?

``` r
library(ggplot2)
library(scales)
library(facetscales)
mydf <- data.frame(
  Subject = rep(c("A", "B", "C", "D"), each = 4),
  Magnitude = rep(c("SomeValue", "Percent", "Scientific", "LogScale"), times = 4),
  Value = c(c(170, 0.60, 2.7E-4, 10000),
            c(180, 0.80, 2.5E-4, 100),
            c(160, 0.71, 3.2E-4, 1000),
            c(159, 0.62, 3.0E-4, 10)))

scales_y <- list(
  Percent = scale_y_continuous(labels = percent_format()),
  SomeValue = scale_y_continuous(),
  Scientific = scale_y_continuous(labels = scientific_format()),
  LogScale = scale_y_log10()
)

ggplot(mydf) +
  geom_point(aes(x = Subject, y = Value)) +
  facet_grid_sc(rows = vars(Magnitude), scales = list(y = scales_y))
```

![](https://i.imgur.com/INz6Ubl.png)

<sup>Created on 2020-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I also attached my sessioninfo():

> R version 3.6.2 (2019-12-12)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> Random number generation:
>  RNG:     Mersenne-Twister 
>  Normal:  Inversion 
>  Sample:  Rounding 
>  
> locale:
> [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
> [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
> [5] LC_TIME=German_Germany.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] facetscales_0.1.0.9000 scales_1.1.0           ggplot2_3.2.1         
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.3       withr_2.1.2      assertthat_0.2.1 crayon_1.3.4    
>  [5] dplyr_0.8.4      grid_3.6.2       R6_2.4.1         lifecycle_0.1.0 
>  [9] gtable_0.3.0     magrittr_1.5     pillar_1.4.3     rlang_0.4.4     
> [13] lazyeval_0.2.2   rstudioapi_0.11  tools_3.6.2      glue_1.3.1      
> [17] purrr_0.3.3      munsell_0.5.0    yaml_2.2.1       compiler_3.6.2  
> [21] pkgconfig_2.0.3  colorspace_1.4-1 tidyselect_1.0.0 tibble_2.1.3

**Comment by zeehio** [comment] 2020-02-28 11:26
If it works under the reprex package and it doesn't work in your R environment, then I guess the issue is with your R environment or something and not related to facetscales.

I wish I could be of more help.

**Comment by ljwright** [comment] 2020-05-08 11:43
I was having a similar issue.

I think the source was adjusting the y-axes while facetting over columns, or adjusting the x-axis which facetting over rows.

Amending the example in the vignette:
```
ggplot(mydf) +
  geom_point(aes(x = Subject, y = Value)) +
  facet_grid_sc(rows = vars(Magnitude), scales = list(y = scales_y)) # This works

ggplot(mydf) +
  geom_point(aes(x = Subject, y = Value)) +
  facet_grid_sc(cols = vars(Magnitude), scales = list(y = scales_y)) # This doesn't
```

**Comment by zeehio** [comment] 2022-11-07 10:51
I don't think maintaining this project is a good idea for reasons outlined in the readme. Therefore I am closing all issues and pull requests and archiving the project. Feel free to fork and maintain this if you like.

**Closed as completed by zeehio** 2022-11-07 10:51 UTC
