### ISSUE TITLE
Scale transformations per facet don't work

### ISSUE THREAD

**Issue by hadrienj** [zeehio/facetscales#3] opened 2018-07-31 10:25 UTC
Hi,
Thank you for your package! I try to set the x and y axes with:

```
scales_y <- list(
  `Score` = scale_y_continuous(),
  `Trial duration (s)` = scale_y_continuous(),
  `Accuracy (%)` = scale_y_continuous(limits=c(0.1, 50), trans='log2'))

scales_x <- list(
  `Score` = scale_x_continuous(),
  `Trial duration (s)` = scale_x_continuous(),
  `Accuracy (%)` = scale_x_continuous(limits=c(0.1, 50), trans='log2'))

facet_grid_sc(rows = vars(metric), scales = list(y = scales_y, x = scales_x))
```

But I get the following message:

```
Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index
```

**Comment by zeehio** [comment] 2018-07-31 16:14
`trans=` is not working properly yet. This may be the cause of the error. To be sure this is the issue I'd need a reproducible example (ideally using a small synthetic dataset).

I am looking into it, although I'm having a baby this week so it may take a while before I can fix it.

**Comment by hadrienj** [comment] 2018-08-01 06:57
Hi,

Thank you for your answer!

Here is a reproducible example. You can use the following dataset:

```
structure(list(name = structure(c(1L, 2L, 3L, 4L, 5L, 6L, 7L, 
8L, 9L, 10L, 11L, 12L, 13L, 14L, 1L, 2L, 3L, 4L, 5L, 6L, 7L, 
8L, 9L, 10L, 11L, 12L, 13L, 14L, 1L, 2L, 3L, 4L, 5L, 6L, 7L, 
8L, 9L, 10L, 11L, 12L, 13L, 14L), .Label = c("p1", "p2", "p3", 
"p4", "p5", "p6", "p7", "p8", "p9", "p10", "p11", "p12", "p13", 
"p14"), class = "factor"), firstVal = c(754.047170745808, 774.165776149175, 
764.258360299831, 878.330954378854, 829.628158083585, 905.362916184883, 
988.819814610189, 992.64354644467, 935.574558784429, 1010.31892644662, 
747.931267607006, 952.95308958631, 987.296641940328, 1072.64132219308, 
8.54568, 13.8015, 18.329, 16.7797894736842, 9.97135294117647, 
13.9316666666667, 13.8067307692308, 14.4062857142857, 9.74760606060606, 
6.30885, 10.341962962963, 9.04691304347826, 7.94832258064516, 
5.61295, 8.69807248557037, 5.90486178462007, 5.59552494176495, 
2.91546613988914, 5.0580582419949, 2.84170506717281, 1.2499621380044, 
1.09934839538025, 2.81939810401559, 2.35898628062062, 7.6277626044263, 
2.57664209061652, 2.10225379321824, 1.00081779515969), lastVal = c(830.029745466412, 
804.324039189462, 918.734069759699, 726.75654646544, 915.438633726968, 
965.26760158898, 1001.54365879925, 1007.85968478831, 893.399447354417, 
1062.57479958659, 991.841726087943, 902.430958136972, 956.201628137288, 
940.399364967424, 8.77866666666667, 8.32856, 14.5282941176471, 
13.4690555555556, 5.74212121212121, 11.4322, 10.0772, 13.96365, 
8.8423125, 6.59215384615385, 10.8560384615385, 11.7311363636364, 
9.28096666666667, 4.58030769230769, 5.6081452987594, 5.70686164447299, 
2.6973566697747, 8.65466673530401, 4.30701664067004, 1.97372399526049, 
1.5277651816278, 0.939670026007678, 4.72413758525327, 1.01808827514295, 
1.6214795070279, 4.78721985332582, 2.52505709554388, 5.38375675479132
), metric = c("Score", "Score", "Score", "Score", "Score", "Score", 
"Score", "Score", "Score", "Score", "Score", "Score", "Score", 
"Score", "Trial duration (s)", "Trial duration (s)", "Trial duration (s)", 
"Trial duration (s)", "Trial duration (s)", "Trial duration (s)", 
"Trial duration (s)", "Trial duration (s)", "Trial duration (s)", 
"Trial duration (s)", "Trial duration (s)", "Trial duration (s)", 
"Trial duration (s)", "Trial duration (s)", "Accuracy (%)", "Accuracy (%)", 
"Accuracy (%)", "Accuracy (%)", "Accuracy (%)", "Accuracy (%)", 
"Accuracy (%)", "Accuracy (%)", "Accuracy (%)", "Accuracy (%)", 
"Accuracy (%)", "Accuracy (%)", "Accuracy (%)", "Accuracy (%)"
)), row.names = c(NA, -42L), class = "data.frame", .Names = c("name", 
"firstVal", "lastVal", "metric"))
```

and create the scales

```
scales_y <- list(
  `Score` = scale_y_continuous(),
  `Trial duration (s)` = scale_y_continuous(),
  `Accuracy (%)` = scale_y_continuous(limits=c(0.1, 50), trans='log2'))

scales_x <- list(
  `Score` = scale_x_continuous(),
  `Trial duration (s)` = scale_x_continuous(),
  `Accuracy (%)` = scale_x_continuous(limits=c(0.1, 50), trans='log2'))
```

I want one facet to have a log scale but not the others. This is working for the y-axis:

```
ggplot(data=test, aes(x=firstVal, y=lastVal, color=name)) +
  geom_point() +
  facet_grid_sc(rows = vars(metric), scales = list(y = scales_y))
```

but not for the x-axis:

```
ggplot(data=test, aes(x=firstVal, y=lastVal, color=name)) +
  geom_point() +
  facet_grid_sc(rows = vars(metric), scales = list(x = scales_x))
```

**Comment by zeehio** [comment] 2018-08-01 17:50
I see two issues:
- `trans` does not work as expected (I'm working on it, more difficult than expected) (Question 2 of #1)
- x/y differences

With respect to the  x/y differences and the `x-axis` not working, here is my feedback:

Your code on the `y-axis` (despite the `trans = "log2"` as you say):

```r
ggplot(data=test, aes(x=firstVal, y=lastVal, color=name)) +
  geom_point() +
  facet_grid_sc(rows = vars(metric), scales = list(y = scales_y))
```
![imatge](https://user-images.githubusercontent.com/75441/43538813-580f7166-95c3-11e8-93f6-15ff03e123ac.png)

Your code on the `x-axis` (despite the `trans = "log2"` as you say):

```r
ggplot(data=test, aes(x=firstVal, y=lastVal, color=name)) +
  geom_point() +
  facet_grid_sc(cols = vars(metric), scales = list(x = scales_x))
```
(Note how I am using `cols` instead of `rows` in `facet_grid_sc` when I want multiple x plots, the same syntax `facet_grid` uses)

![imatge](https://user-images.githubusercontent.com/75441/43538724-14ea03ce-95c3-11e8-8ab8-ad6915183fc8.png)

If you want something different in the output (besides the `trans = "log2"` missing feature) feel free to ask for it. I know I should clarify the error message (the subset blahblahblah error does not help to know there is something wrong with rows/cols).

**Comment by hadrienj** [comment] 2018-08-01 18:22
Oh I see! Actually, I needed to have one of the facets with a log scale y-axis but not the others. Looks like I'll need to find another solution :)
Thank you!

**Comment by Make42** [comment] 2018-09-21 12:26
I have the same request (which is the reason I wanted to use this package): I need to have one x-axis to be on log10-scale and the other on the normal linear scale. It would be nice to have this feature implemented.

(Congrats, to the baby, by the way!! Hope, she or he is healthy!)

**Comment by zeehio** [comment] 2018-09-21 12:53
The more I look into this the more complicated it is... I would need to patch the base ggplot2 package and I am still trying to figure out what is the best path to make everything work as expected.

I guess you may have explored alternatives like the cowplot package [Shared legends](https://cran.r-project.org/web/packages/cowplot/vignettes/shared_legends.html). What features do you miss from it?

**Comment by Make42** [comment] 2018-09-21 13:23
I guess it is also possible to work with identical breaks, labels, limits etc. and then build one cowplot. The big advantage of your package is, that you only handle one ggplot and with that comes, that I only have to set the theme once (which is a long list in my case).

**Comment by zeehio** [comment] 2018-09-21 13:52
Thanks @Make42. I may need to explore a way other than a facet to address this issue.

It is good for me to know that the main advantage of this package over the alternatives is the interface (one ggplot call, etc), so I know what solutions are best.

Thanks again!

**Comment by oyhx** [comment] 2018-10-25 07:31
Hi Zeehio, is there any update to the package to address the issue highlighted earlier?

**Comment by zeehio** [comment] 2018-10-25 08:54
So far I reached a point were fixing this seems to require changes to ggplot2, because facets were not designed for this, and unfortunately I do not have the time to work on this issue right now.

If you need different transformations to each facet, use the cowplot package to combine the plots

On the other hand, cowplot provides a good alternative, as mentioned above. That package is the best workaround I have found to address this issue

**Comment by teunbrand** [comment] 2019-09-01 15:27
I have some ideas about how this could be implemented, but it would come at the trade-off that the out of bounds (`oob`) arguments will be overridden. Would you consider it if I were to write up a pull request?

**Comment by zeehio** [comment] 2019-09-01 19:11
Yes, sure! I'll do my best to review and merge pull requests! 👍 Thanks!

**Comment by zeehio** [comment] 2019-09-02 07:37
Thank you @teunbrand. 

``` r
  
library(facetscales)
library(ggplot2)
df <- data.frame(x = c(1,2,3,4, 1, 2, 3, 4),
                 y = c(1, 2, 3, 4, 10, 100, 1000, 10000),
                 z = c(rep("a", 4), rep("b", 4)),
                 stringsAsFactors = FALSE)

ggplot(df) +
  geom_point(aes(x = x, y = y, color = z)) +
  facet_grid(rows = vars(z),
             scales = "free_y") +
  labs(title = "With ggplot2 (facet_grid)")
```

![](https://i.imgur.com/M7reAsC.png)

``` r

ggplot(df) +
  geom_point(aes(x = x, y = y, color = z)) +
  facet_grid_sc(rows = vars(z),
                scales = list(y = list(a = scale_y_continuous(),
                                       b = scale_y_continuous(trans = "log10")))) +
  labs(title = "With facetscales (facet_grid_sc)")
```

![](https://i.imgur.com/aPob4EJ.png)

<sup>Created on 2019-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Closing this :+1:

**Closed as completed by zeehio** 2019-09-02 07:37 UTC
Labels: requires-ggplot2-changes, has-workaround, pull-request-welcome
