### ISSUE TITLE
Error when using date column for x-axis

### ISSUE THREAD

**Issue by gacolitti** [zeehio/facetscales#13] opened 2020-01-27 17:11 UTC
Shouldn't this work:

```
library(ggplot2)
library(scales)
library(facetscales)
mydf <- data.frame(
  Date = rep(as.Date(c("2020-01-01", "2020-01-02", "2020-01-03", "2020-01-04")), each = 4),
  Magnitude = rep(c("SomeValue", "Percent", "Scientific", "LogScale"), times = 4),
  Value = c(c(170, 0.60, 2.7E-4, 10000),
            c(180, 0.80, 2.5E-4, 100),
            c(160, 0.71, 3.2E-4, 1000),
            c(159, 0.62, 3.0E-4, 10)))

scales_y <- list(
  Percent = scale_y_continuous(labels = percent_format()),
  SomeValue = scale_y_continuous(),
  Scientific = scale_y_continuous(labels = scientific_format()),
  LogScale = scale_y_log10()
)

ggplot(mydf) +
  geom_point(aes(x = Date, y = Value)) +
  facet_grid_sc(rows = vars(Magnitude), scales = list(y = scales_y))
```

**Comment by zeehio** [comment] 2020-01-28 13:41
Thanks for the reproducible bug report.

I was able to see that this code was working until #9 was merged.

@teunbrand, since you wrote that pull request, do you know why this may happen?

I will try to find time to fix this

**Comment by teunbrand** [comment] 2020-01-28 16:45
Assuming you've executed the reprex, the following also doesn't work:

```
mydf2 <- cbind(mydf, Time = Sys.time() + rep(1:4, each = 4))

ggplot(mydf2) +
  geom_point(aes(x = Time, y = Value)) +
  facet_grid_sc(rows = vars(Magnitude), scales = list(y = scales_y))
```

Which makes me think this is a type stability issue with the POSIXct / Date classes. For example the `log10_trans()` takes numerical input and returns numerical output, whereas the `date_trans()` takes Date-class input and returns numerical output. I've debugged a bit and it seems like at the point where facetscales is executing the `finish_data` ggproto-method, numerical input is given to the date transformer, which then throws an error. 

I don't know exactly why we've had date transformations prior to the `finish_data` bit and not for example log-transforms. I don't think there are combinations of date scales and actual transformations, so a very ad-hoc solution could be to just skip transforming if the transformer is for dates and times. I haven't tested this but it seems if the bit in `finish_data` is replaced by the following, it might work.

```
# Transform variables by appropriate scale
for (j in y_vars) {
  yscale <- y_scales[[yidx]]
  if (!(yscale$trans$name %in% c("date", "time"))) {
    dat[, j] <- y_scales[[yidx]]$transform(dat[, j])
  }
}
for (j in x_vars) {
  xscale <- x_scales[[xidx]]
  if (!(xcale$trans$name %in% c("date", "time"))) {
    dat[, j] <- x_scales[[xidx]]$transform(dat[, j])
  }
}
```

I also have some code that relies on this formulation of the finish data, so I'll probably investigate more deeply at some point.

**Comment by zeehio** [comment] 2022-11-07 10:51
I don't think maintaining this project is a good idea for reasons outlined in the readme. Therefore I am closing all issues and pull requests and archiving the project. Feel free to fork and maintain this if you like.

Apologies for not having responded earlier. It took me a while to decide that archiving was necessary.

**Closed as completed by zeehio** 2022-11-07 10:51 UTC
